package TrainTicketBooking;

import java.io.File;
import java.sql.*;
import java.util.Random;
import javax.swing.*;
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        To = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        General = new javax.swing.JComboBox<>();
        Classes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Day = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        Year = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Book Ticket");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(231, 10, 192, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("From :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 85, 60, 17);

        From.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        From.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromActionPerformed(evt);
            }
        });
        jPanel1.add(From);
        From.setBounds(88, 82, 364, 23);

        To.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToActionPerformed(evt);
            }
        });
        jPanel1.add(To);
        To.setBounds(88, 145, 364, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("To : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 148, 60, 17);

        General.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        General.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERAL", "LADIES", "LOWER BERTH/SR.CITIZEN", "DIVYAANG", "TATKAL", "PREMIUM TATKAL" }));
        General.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneralActionPerformed(evt);
            }
        });
        jPanel1.add(General);
        General.setBounds(88, 210, 364, 23);

        Classes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Classes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Classes ", "Anubhti Class (EA)", "AC First Class (1A)", "Exec.Chair Car (EC)", "AC 2 Tier (2A)", "First Class (FC)", "AC 3 Tier (3A)", "AC 3 Economy (3E)", "AC Chair Car (CC)", "Sleeper (SL)", "Second SItting(2S)" }));
        Classes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassesActionPerformed(evt);
            }
        });
        jPanel1.add(Classes);
        Classes.setBounds(482, 144, 179, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Date : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 85, 50, 17);

        cb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb.setText("Divyaang Consession");
        cb.setOpaque(false);
        cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemStateChanged(evt);
            }
        });
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        jPanel1.add(cb);
        cb.setBounds(88, 261, 173, 25);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("Flexible With Date");
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(279, 261, 173, 25);

        cb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb1.setText("Train With Available Berth");
        cb1.setToolTipText("Space to Sleep");
        cb1.setOpaque(false);
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb1);
        cb1.setBounds(454, 261, 207, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(279, 317, 80, 31);

        jLabel9.setText("All Classes :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(486, 125, 86, 14);

        Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(Day);
        Day.setBounds(520, 85, 56, 20);

        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sub", "Oct", "Nov", "Dec" }));
        Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthActionPerformed(evt);
            }
        });
        jPanel1.add(Month);
        Month.setBounds(585, 85, 65, 20);

        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jPanel1.add(Year);
        Year.setBounds(660, 85, 61, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToActionPerformed

    private void FromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromActionPerformed

    private void GeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneralActionPerformed
     
    }//GEN-LAST:event_GeneralActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
       
        if(cb.isSelected()){    
JOptionPane.showMessageDialog(this,"Specially abled availing the concession need to carry Photo Identity card issued by Railways which is to be produced for On-board / off-board verification during journey. Escort passengers also need to carry photo identity card mentioned at the time of booking.");    
        }  
    }//GEN-LAST:event_cbActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Ticket t=new Ticket();
        Signin s = new Signin();
        Ticket.jt.setText(Reservation.From.getText().trim());
        Ticket.jt1.setText(Reservation.To.getText().trim());
        Ticket.jt2.setText(Reservation.Day.getSelectedItem().toString()+" "+Reservation.Month.getSelectedItem()+" "+Reservation.Year.getSelectedItem().toString());
        Ticket.jt3.setText(Reservation.Classes.getSelectedItem().toString());
//        Random ran= new Random();
//       int n=ran.nextInt(100000)+1;
//       String val=String.valueOf(n);
//       Ticket.jt4.setText(Reservation);
        t.setVisible(true);
        
     
       String d=null;
       
       System.out.println(d);
       String d0=From.getText().trim();
       String d1=To.getText().trim();
       String d2=Day.getSelectedItem().toString();
       String d3=Month.getSelectedItem().toString();
       String d4=Year.getSelectedItem().toString();
       String d5=General.getSelectedItem().toString();
       String d6=Classes.getSelectedItem().toString();
       File f = new File("12.jpeg");
    
       
         try{
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","root","");
              Statement st=con.createStatement();
               st.execute("insert into bookings values('"+d+"','"+d0+"','"+d1+"','"+d2+"','"+d3+"','"+d4+"','"+d5+"','"+d6+"','"+f+"')");
//                String sql="UPDATE bookings SET fro = ?, too = ? ,day = ?, month = ? year = ? general=? class=? WHERE username = ?";
//               PreparedStatement pst = con.prepareStatement(sql);
//               pst.setString(1,d0);
//               pst.setString(2,d1);
//               pst.setString(3,d2);
//               pst.setString(4,d3);
//               pst.setString(5,d4);
//               pst.setString(6,d5);
//               pst.setString(7,d6);
//               pst.setString(8,d);
//               ResultSet rs = pst.executeQuery();
              }catch(SQLException ex) {
              JOptionPane.showMessageDialog(null, ex);
              }
          
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassesActionPerformed
      
       
    }//GEN-LAST:event_ClassesActionPerformed

    private void cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbItemStateChanged

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cb1ItemStateChanged

    private void MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        
    }//GEN-LAST:event_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Classes;
    public static javax.swing.JComboBox<String> Day;
    public static javax.swing.JTextField From;
    public static javax.swing.JComboBox<String> General;
    public static javax.swing.JComboBox<String> Month;
    public static javax.swing.JTextField To;
    public static javax.swing.JComboBox<String> Year;
    private javax.swing.JCheckBox cb;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
