package TrainTicketBooking;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ashish
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    JLabel label= new JLabel();
    public Ticket() {
        initComponents();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jt = new javax.swing.JTextField();
        jt1 = new javax.swing.JTextField();
        jt2 = new javax.swing.JTextField();
        jt3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jt4 = new javax.swing.JTextField();
        Download = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jt.setEditable(false);
        jt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jt.setBorder(null);
        jt.setOpaque(false);
        jPanel2.add(jt);
        jt.setBounds(30, 250, 260, 22);

        jt1.setEditable(false);
        jt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jt1.setBorder(null);
        jt1.setOpaque(false);
        jPanel2.add(jt1);
        jt1.setBounds(30, 290, 180, 22);

        jt2.setEditable(false);
        jt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jt2.setBorder(null);
        jt2.setOpaque(false);
        jPanel2.add(jt2);
        jt2.setBounds(280, 290, 140, 22);

        jt3.setEditable(false);
        jt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jt3.setBorder(null);
        jt3.setOpaque(false);
        jPanel2.add(jt3);
        jt3.setBounds(30, 140, 140, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrainTicketBooking/Ticket.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 50, 500, 330);

        jt4.setEditable(false);
        jt4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jt4.setToolTipText("Booking Number");
        jt4.setOpaque(false);
        jPanel2.add(jt4);
        jt4.setBounds(370, 279, 130, 30);

        Download.setText("Download");
        Download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(Download)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Download)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadActionPerformed
         try {
             JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File("."));
             int response = fileChooser.showSaveDialog(null);
         
            SaveScreenShot(jPanel2,fileChooser.getSelectedFile().toString());
            JOptionPane.showMessageDialog(null, "Downloaded");
           
        } catch (Exception ex) {
           
        }
    }//GEN-LAST:event_DownloadActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Ticket().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Download;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField jt;
    public static javax.swing.JTextField jt1;
    public static javax.swing.JTextField jt2;
    public static javax.swing.JTextField jt3;
    public static javax.swing.JTextField jt4;
    // End of variables declaration//GEN-END:variables

    public static BufferedImage getScreenShot(Component component)
    {
        BufferedImage image = new BufferedImage(component.getWidth(),component.getHeight(),BufferedImage.TYPE_INT_RGB);
        component.paint(image.getGraphics());
        return image;
    }
    private void SaveScreenShot(Component component,String filename)throws Exception
    {
      BufferedImage img = getScreenShot(component);
      ImageIO.write(img,"jpeg", new File(filename));
      
    }
}
